services:
    app:
        build:
            args:
                user: sanjorno
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: ThousandIT_API
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - project

    db:
        image: mysql:8.0
        container_name: ThousandIT_API-DB
        restart: unless-stopped
        ports:
            -   3306:3306
        environment:
            MYSQL_DATABASE: ThousandIT_API
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker-compose/mysql:/var/lib/mysql
        networks:
            - project
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    nginx:
        image: nginx:alpine
        container_name: ThousandIT_API-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - project

networks:
    project:
        driver: bridge
